# Generated by Django 4.0.2 on 2022-03-22 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='example recipe', max_length=50)),
                ('intro', models.CharField(max_length=100)),
                ('time', models.DurationField(default=datetime.timedelta(seconds=1200))),
            ],
        ),
        migrations.CreateModel(
            name='RecipeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=-1)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordofmouth.recipe')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('recipeblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wordofmouth.recipeblock')),
                ('src', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('wordofmouth.recipeblock',),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('recipeblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wordofmouth.recipeblock')),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('wordofmouth.recipeblock',),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('recipeblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wordofmouth.recipeblock')),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('wordofmouth.recipeblock',),
        ),
    ]
