# Generated by Django 4.0.2 on 2022-03-24 12:58

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
    ]
