# Generated by Django 4.0.2 on 2022-03-27 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordofmouth', '0004_alter_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likenum',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
