# Generated by Django 4.0.2 on 2022-03-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0005_recipe_likenum_remove_recipe_likes_recipe_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likenum',
        ),
    ]
