# Generated by Django 4.0.2 on 2022-04-10 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordofmouth', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='child', to='wordofmouth.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='parent',
            field=models.ManyToManyField(blank=True, to='wordofmouth.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
