# Generated by Django 4.0.3 on 2022-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0010_recipe_children_recipe_parent_alter_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
