# Generated by Django 4.0.2 on 2022-04-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0012_remove_recipe_username_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='text',
            new_name='name',
        ),
    ]
