# Generated by Django 4.0.2 on 2022-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0013_rename_text_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
