# Generated by Django 4.0.2 on 2022-04-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0015_alter_recipe_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeblock',
            name='pos',
        ),
    ]
