# Generated by Django 4.0.2 on 2022-04-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0017_alter_ingredient_quantity_alter_recipe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='lb', max_length=50),
        ),
    ]
