# Generated by Django 4.0.2 on 2022-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0021_alter_comment_commenttext_alter_step_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentText',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='intro',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='step',
            name='text',
            field=models.CharField(max_length=4000),
        ),
    ]
